#This file was originally generated by PyScripter's unitest wizard

import unittest
import scheme

class TestSchemeFile(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test__init__(self):
        pass

    def testPanelDetails(self):
        pass

    def testBoundaryDetails(self):
        pass

    def testExcesDetails(self):
        pass

if __name__ == '__main__':
    unittest.main()
